### PR TITLE
Enable metrics for cordova project

### PR DESCRIPTION
**Pull request by edewit**
@matzew Enable metrics

### CODE REVIEW

**Comment by matzew** [comment]
@edewit :eyes:

**Comment by matzew** [comment]
Getting the following error when doing `cordova run android` (before I updated the JSON config and did do `cordova platform add android`:

```
/Users/matzew/ANDROID_HOME/current/tools/ant/build.xml:597: The following error occurred while executing this line:
/Users/matzew/ANDROID_HOME/current/tools/ant/build.xml:649: The following error occurred while executing this line:
/Users/matzew/ANDROID_HOME/current/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/Users/matzew/Work/JBoss/HelloWorld/unified-push-helloworld/cordova/platforms/android/CordovaLib/${aapt}" (in directory "/Users/matzew/Work/JBoss/HelloWorld/unified-push-helloworld/cordova/platforms/android/CordovaLib"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
    at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
    at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
    at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
    at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
    at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
    at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:306)
    at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:221)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 68 more

Total time: 1 second

/Users/matzew/Work/JBoss/HelloWorld/unified-push-helloworld/cordova/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
```

**Comment by edewit** [comment]
@matzew seems there is something wrong with your android platform directory could you run:

``` bash
cordova platform rm android
cordova platform add android
```

And try again?

**Comment by matzew** [comment]
ok, can try - but I did that on a fresh checkout

On Mon, Jun 15, 2015 at 3:56 PM, Erik Jan de Wit notifications@github.com
wrote:

> @matzew https://github.com/matzew seems there is something wrong with
> your android platform directory could you run:
> 
> cordova platform rm android
> cordova platform add android
> 
> And try again?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-mobile/unified-push-helloworld/pull/13#issuecomment-112079623
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@edewit, same issue

On Mon, Jun 15, 2015 at 3:56 PM, Erik Jan de Wit notifications@github.com
wrote:

> @matzew https://github.com/matzew seems there is something wrong with
> your android platform directory could you run:
> 
> cordova platform rm android
> cordova platform add android
> 
> And try again?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-mobile/unified-push-helloworld/pull/13#issuecomment-112079623
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by edewit** [comment]
do you have android home set?

**Comment by matzew** [comment]
yup

On Mon, Jun 15, 2015 at 4:09 PM, Erik Jan de Wit notifications@github.com
wrote:

> do you have android home set?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jboss-mobile/unified-push-helloworld/pull/13#issuecomment-112082449
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
@danielpassos @sebastienblanc mind taking a look?

**Comment by secondsun** [comment]
X post from ML

Google broke ant in Android.  This means that, among other things, Cordova is broken if you are using the latest tooling.  HOWEVER, I found a workaround and this is tracked in Android's bug tracker.

If you are seeing an error along the lines of ${aapt} can not be found then this affects you.

First the workaround : 

add 

```
    <property name="aapt" location="${sdk.dir}/build-tools/22.0.1/aapt" />
    <property name="aidl" location="${sdk.dir}/build-tools/22.0.1/aidl" />
    <property name="dx" location="${sdk.dir}/build-tools/22.0.1/dx" />
    <property name="zipalign" location="${sdk.dir}/build-tools/22.0.1/zipalign" />
```

to $ANDROID_HOME/tools/ant/build.xml 

Second, Google's bug report for tracking : 

https://code.google.com/p/android/issues/detail?id=176488

**Pull request merged**
