### PR TITLE
Gcm 3 update

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@secondsun updated this finallu :)

did revert your revert, and update the versions to non -SNAPSHOT (aka finals).

rebased to have one commit...

**Comment by secondsun** [comment]
@matzew I found a regression in the push library.  It isn't a catastrophic problem, but a big enough one I think we should hold off on merging this until we get a patch released on maven central.  See AGDROID-541

**Comment by matzew** [comment]
@secondsun I've updated, using 3.0.1 of push

**Comment by matzew** [comment]
@secondsun wanna merge this too ?

**Comment by secondsun** [comment]
@matzew Done!

**Pull request merged**
