### PR TITLE
Introduce plist config for registration

### PR DESCRIPTION
**Pull request by corinnekrych**
To test both ios and objc version.
This PR contain the AeroGearPush.framework with plist configuration
@sebastienblanc mind to review?

### CODE REVIEW

**Comment by corinnekrych** [comment]
@danielpassos @edewit do you mind to review? are you also planning to update android windows demo app with new config file?

**Comment by danielpassos** [comment]
I will review it tomorrow (today is a holiday) and yes, see: https://github.com/danielpassos/unified-push-helloworld/tree/push-config

**Comment by corinnekrych** [comment]
Thanks @danielpassos

**Comment by matzew** [comment]
@corinnekrych is this using latest? Or does it need an update ?

**Comment by corinnekrych** [comment]
@matzew nope. Let me update for latest....
WIP

**Comment by corinnekrych** [comment]
@danielpassos @matzew updated with latest libs ios-switch and ios-objc

**Comment by corinnekrych** [comment]
@danielpassos @matzew ok to merge?

**Comment by matzew** [comment]
sure thing!

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
