### PR TITLE
[Android]: Metrics

### PR DESCRIPTION
**Pull request by danielpassos**
See: [AGPUSH-1415](https://issues.jboss.org/browse/AGPUSH-1415)

To test it you will need build [aerogear-android-push](http://github.com/aerogear/aerogear-android-push locally)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @matzew @sebastienblanc Could you give it a spin?

**Comment by danielpassos** [comment]
As talked with @matzew on IRC I've changed it to send metrics only when message come from background (aka notification bar)

**Comment by matzew** [comment]
@cvasilak if time permits, do you mind taking a look here too ?

**Comment by cvasilak** [comment]
tested and can see the metric information date, updated only when the notification is clicked in the notification bar and the app is brought in the foreground.

:+1:

**Comment by secondsun** [comment]
OH hey yeah totally for got to mention here.
It works great and sends everything right.  
+1

**Pull request merged**
