### PR TITLE
Agpush 1414.analytics.demos

### PR DESCRIPTION
**Pull request by corinnekrych**
Demos app for analytics. 
ios-objc test ios-push in ObjC version in ios 7.x 
ios-swift test ios-push in Swift version for ios 8.x

### CODE REVIEW

**Comment by cvasilak** [comment]
noticed when running the application a warning print out in the console:

```
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:],
 but you still need to add "remote-notification" to the list of your supported 
UIBackgroundModes in your Info.plist.
```

Since we are using this `didReceive*` variant, and regardless where we don't exercise "content-available", I think we can enable this capability to avoid it.

**Comment by cvasilak** [comment]
apart from this comment demo worked and can see the metric date being updated in the UPS console :+1:

**Comment by cvasilak** [comment]
noticed that the `swift` branch is merged also in this PR altogether but it fails to include the gilt history.

I believe this should be done on separate PR and once we are happy with the demos (both objc/swift) variant to have a final PR with the merge of those branches.

**Comment by corinnekrych** [comment]
As discussed in meeting, I said I will close https://github.com/jboss-mobile/unified-push-helloworld/pull/6
and open a new demos PR with both objc and swift version.

**Comment by matzew** [comment]
@corinnekrych @cvasilak is this good for merging ?

**Comment by corinnekrych** [comment]
@matzew ready to merge. Just added configuration as suggested.

**Comment by matzew** [comment]
Thanks, landed on master (a9736e9)

**Pull request merged**
