### PR TITLE
To.be.tagged.1.1.0 beta.1

### PR DESCRIPTION
**Pull request by corinnekrych**
@matzew and to finish demo app with latest binaries both Swift and ObjC

### CODE REVIEW

**Comment by matzew** [comment]
@corinnekrych now we can tag ?

**Comment by corinnekrych** [comment]
@matzew let's merge https://github.com/jboss-mobile/unified-push-helloworld/pull/9 and https://github.com/jboss-mobile/unified-push-helloworld/pull/11
and then we can tag this demo repo 1.1.0-beta.1 as it will contain all platforms updated.... ah maybe we missed cordova @edewit ?

**Comment by corinnekrych** [comment]
@matzew swift and objc ios-push libs have been tagged already see:
https://github.com/aerogear/aerogear-ios-push/tree/1.1.0-beta.1-swift
https://github.com/aerogear/aerogear-ios-push/tree/1.1.0-beta.1
and are available on cocoapods

**Comment by matzew** [comment]
@corinnekrych I think we also need the released Windows binary from @edewit and the released JARs from @danielpassos

**Pull request merged**
